import { SiteHeader } from '@/components/landing/site-header'
import { SiteFooter } from '@/components/landing/site-footer'

export default function AIPolicyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <main className="flex-1">
        <div className="mx-auto max-w-3xl px-6 py-24">
          <h1 className="text-4xl font-bold tracking-tight mb-8">AI Policy</h1>
          <div className="prose prose-neutral dark:prose-invert">
            <p className="text-muted-foreground mb-6">
              At CodewithChat, we leverage advanced Artificial Intelligence to help you build production-ready software. This policy outlines our commitment to responsible AI usage.
            </p>
            <h2 className="text-2xl font-semibold mt-10 mb-4">Code Ownership</h2>
            <p className="text-muted-foreground mb-6">
              Any code generated by CodewithChat based on your prompts belongs entirely to you. You are free to use, modify, distribute, and monetize the generated applications without any restrictions or royalties.
            </p>
            <h2 className="text-2xl font-semibold mt-10 mb-4">Data Privacy</h2>
            <p className="text-muted-foreground mb-6">
              Your prompts, ideas, and generated code are private. We do not use your proprietary codebase to train our base AI models. We respect your intellectual property.
            </p>
            <h2 className="text-2xl font-semibold mt-10 mb-4">Accuracy and Reliability</h2>
            <p className="text-muted-foreground mb-6">
              While our AI is highly advanced and specializes in Next.js, TypeScript, and Supabase, it is a tool meant to augment your development process. We recommend reviewing the generated code before deploying it to production environments.
            </p>
          </div>
        </div>
      </main>
      <SiteFooter />
    </div>
  )
}
