import { SiteHeader } from '@/components/landing/site-header'
import { SiteFooter } from '@/components/landing/site-footer'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'

const faqs = [
  {
    question: "What is CodewithChat?",
    answer: "CodewithChat is an AI-powered software engineering platform that helps you build full-stack web applications simply by describing your ideas in natural language."
  },
  {
    question: "What tech stack does the AI use?",
    answer: "Our AI is specialized in building modern, scalable applications using Next.js, TypeScript, Tailwind CSS, and Supabase. This ensures your app is production-ready from day one."
  },
  {
    question: "Do I own the code generated by the AI?",
    answer: "Yes! You own 100% of the code generated by our AI based on your prompts. You are free to monetize, distribute, and modify it without any restrictions."
  },
  {
    question: "Do I need to know how to code?",
    answer: "No coding experience is required to build your MVP! However, our platform also serves as a System Design Mentor, making it a great tool for beginners who want to learn how real software is built."
  }
]

export default function FAQsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <main className="flex-1">
        <div className="mx-auto max-w-3xl px-6 py-24">
          <h1 className="text-4xl font-bold tracking-tight mb-8 text-center">Frequently Asked Questions</h1>
          <p className="text-center text-muted-foreground mb-12">
            Everything you need to know about CodewithChat.
          </p>
          
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left">{faq.question}</AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </main>
      <SiteFooter />
    </div>
  )
}
